export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
export const SET_PAGE = 'SET_PAGE';
export const SET_SELECTED = 'SET_SELECTED';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const FETCH_TEMPLATES = 'FETCH_TEMPLATES';
